# Generated by Django 5.2.3 on 2025-06-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0002_subscriptionemailtemplate_subscriptionuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscriptionuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='subscriptionuser',
            name='joined_at',
        ),
        migrations.RemoveField(
            model_name='subscriptionuser',
            name='message',
        ),
    ]
