# Generated by Django 5.2.3 on 2025-06-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0003_message_remove_subscriptionuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='events/thumbnails/'),
        ),
    ]
