# Generated by Django 5.2.3 on 2025-06-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0005_upcomingevent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='occasion_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
