# Generated by Django 5.2.3 on 2025-06-27 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0006_galleryitem_occasion_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
