# Generated by Django 5.2.3 on 2025-07-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coord', '0011_jobapplication_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='branch',
            field=models.CharField(choices=[('All Branches', 'All Branches'), ('Golden Tulip, DSM', 'Golden Tulip, DSM'), ('Sea Shells, DSM', 'Sea Shells, DSM'), ('Arusha, DSM', 'Arusha, DSM')], default='All Branches', max_length=255),
        ),
    ]
